-- Insertion d'enseignants de démo supplémentaires (en évitant les doublons)

INSERT INTO teachers (first_name, last_name, email, status) VALUES
('Pascale', 'Wauters', 'pascale.wauters@uclouvain.be', 'Actif'),
('Benjamin', 'Elias', 'benjamin.elias@uclouvain.be', 'Actif'),
('Jean-François', 'Gohy', 'jean-francois.gohy@uclouvain.be', 'Actif'),
('Charles', 'De Smet', 'charles.desmet@uclouvain.be', 'Actif'),
('Christophe', 'Pierreux', 'christophe.pierreux@uclouvain.be', 'Actif'),
('Guido', 'Bommer', 'guido.bommer@uclouvain.be', 'Actif'),
('Marie', 'Boucquey', 'marie.boucquey@uclouvain.be', 'Actif'),
('Jean-François', 'Collet', 'jean-francois.collet@uclouvain.be', 'Actif'),
('Jean Baptiste', 'Demoulin', 'jean-baptiste.demoulin@uclouvain.be', 'Actif'),
('Catherine', 'Behets Wydemans', 'catherine.behets@uclouvain.be', 'Actif'),
('Benoît', 'Lengelé', 'benoit.lengele@uclouvain.be', 'Actif'),
('Stefan', 'Constantinescu', 'stefan.constantinescu@uclouvain.be', 'Actif'),
('Donatienne', 'Tyteca', 'donatienne.tyteca@uclouvain.be', 'Actif'),
('Philippe', 'Gailly', 'philippe.gailly@uclouvain.be', 'Actif'),
('Miikka', 'Vikkula', 'miikka.vikkula@uclouvain.be', 'Actif'),
('Laurent', 'Gatto', 'laurent.gatto@uclouvain.be', 'Actif'),
('Catherine', 'Legrand', 'catherine.legrand@uclouvain.be', 'Actif'),
('Olivier', 'Servais', 'olivier.servais@uclouvain.be', 'Actif'),
('Benoît', 'Boland', 'benoit.boland@uclouvain.be', 'Actif'),
('Séverine', 'Henrard', 'severine.henrard@uclouvain.be', 'Actif'),
('Jean', 'Macq', 'jean.macq@uclouvain.be', 'Actif'),
('Andrea', 'Penaloza-Baeza', 'andrea.penaloza@uclouvain.be', 'Actif'),
('Philippe', 'de Timary', 'philippe.detimary@uclouvain.be', 'Actif'),
('Gérald', 'Deschietere', 'gerald.deschietere@uclouvain.be', 'Actif'),
('Peter', 'Verdée', 'peter.verdee@uclouvain.be', 'Actif'),
('Nicolas', 'Tajeddine', 'nicolas.tajeddine@uclouvain.be', 'Actif'),
('Dominique', 'Vanpee', 'dominique.vanpee@uclouvain.be', 'Actif'),
('Thierry', 'Detaille', 'thierry.detaille@uclouvain.be', 'Actif'),
('Audrey', 'Dieu', 'audrey.dieu@uclouvain.be', 'Actif'),
('Laurent', 'Houtekie', 'laurent.houtekie@uclouvain.be', 'Actif'),
('David', 'Kahn', 'david.kahn@uclouvain.be', 'Actif'),
('Julien', 'Moury', 'julien.moury@uclouvain.be', 'Actif'),
('Nassim', 'Touil', 'nassim.touil@uclouvain.be', 'Actif'),
('Giuseppe', 'Liistro', 'giuseppe.liistro@uclouvain.be', 'Actif'),
('Eric', 'Marchand', 'eric.marchand@uclouvain.be', 'Actif'),
('Catherine', 'Barréa', 'catherine.barrea@uclouvain.be', 'Actif'),
('Karlien', 'Carbonez', 'karlien.carbonez@uclouvain.be', 'Actif'),
('Stéphane', 'Moniotte', 'stephane.moniotte@uclouvain.be', 'Actif'),
('Mieke', 'Roggen', 'mieke.roggen@uclouvain.be', 'Actif'),
('Antoine', 'Froidure', 'antoine.froidure@uclouvain.be', 'Actif')
ON CONFLICT (email) DO NOTHING;