// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbzvsyjurbiiwkioehca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpienZzeWp1cmJpaXdraW9laGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzM0MzEsImV4cCI6MjA2ODQwOTQzMX0.N9JizpZu40IjTZVBhyA5EOrzTe4msJPZmH53xFgj4yI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});